import {
  clarificationResultSchema,
  proposalSchema,
  taskCardSchema,
  type ClarificationResult,
  type Proposal,
  type TaskCard,
} from "@evomind/contracts";

const cards = [
  {
    id: "task-logistics",
    status: "published",
    title: "Прогноз загрузки городских маршрутов",
    context: "Оператор ежедневно планирует выпуск автобусов вручную на основе прошлой недели.",
    need: "Нужно заранее видеть ожидаемую загрузку по маршрутам и временным слотам.",
    users: "Диспетчеры и руководитель транспортного отдела",
    data: "Обезличенные поездки за 18 месяцев, погода и календарь событий",
    constraints: "Локальное размещение, без персональных данных",
    expectedResult: "Дашборд с прогнозом на семь дней и объяснением факторов",
    successCriteria: "Ошибка прогноза MAPE не выше 18% на пилотных маршрутах",
    contact: "Айдана, product@city.example",
    interactionFormat: "Еженедельный созвон и доступ к тестовому контуру",
    topic: "Транспорт",
    score: 94,
    readinessLevel: "priority",
    scoreBreakdown: { contextAndNeed: 20, data: 19, expectedResult: 15, successCriteria: 15, constraints: 8, users: 7, businessContact: 7 },
    missingFields: [],
  },
  {
    id: "task-energy",
    status: "published",
    title: "Поиск аномалий энергопотребления",
    context: "Сеть магазинов получает показания счётчиков, но замечает перерасход только в конце месяца.",
    need: "Выявлять нетипичное потребление в течение суток.",
    users: "Энергоменеджер и директора филиалов",
    data: "Почасовые показания 80 объектов за два года",
    constraints: "Пилот на пяти объектах",
    expectedResult: "Список аномалий с приоритетом и вероятной причиной",
    successCriteria: "Найти не менее 80% известных инцидентов на истории",
    contact: "energy@example.kz",
    interactionFormat: "Доступ к CSV и интервью раз в неделю",
    topic: "Энергетика",
    score: 86,
    readinessLevel: "ready",
    scoreBreakdown: { contextAndNeed: 18, data: 18, expectedResult: 13, successCriteria: 12, constraints: 4, users: 3, businessContact: 3 },
    missingFields: [],
  },
  {
    id: "task-retail",
    status: "published",
    title: "Подсказки для пополнения полок",
    context: "Товар заканчивается на полке раньше, чем персонал получает сигнал.",
    need: "Предупреждать сотрудников о риске пустой полки.",
    users: "Администраторы магазинов",
    data: "Продажи и остатки по 12 магазинам",
    constraints: "Без установки новых камер",
    expectedResult: "Приоритизированный список для пополнения",
    successCriteria: "Сократить out-of-stock на 10%",
    contact: "retail@example.kz",
    interactionFormat: "Пилот на одном магазине",
    topic: "Ритейл",
    score: 73,
    readinessLevel: "ready",
    scoreBreakdown: { contextAndNeed: 16, data: 14, expectedResult: 11, successCriteria: 10, constraints: 4, users: 3, businessContact: 3 },
    missingFields: ["Детализировать формат выгрузки"],
  },
  {
    id: "task-hr",
    status: "published",
    title: "Навигатор адаптации сотрудников",
    context: "Новые сотрудники долго ищут ответы в разрозненных материалах.",
    need: "Упростить поиск информации в первые недели работы.",
    users: "Новые сотрудники",
    data: "База регламентов и FAQ",
    constraints: "Не раскрывать внутренние документы наружу",
    expectedResult: "Поиск с ответами и ссылками на источник",
    successCriteria: "Будет определено после интервью",
    contact: "hr@example.kz",
    interactionFormat: "Два интервью",
    topic: "HR",
    score: 61,
    readinessLevel: "workable",
    scoreBreakdown: { contextAndNeed: 14, data: 12, expectedResult: 10, successCriteria: 3, constraints: 4, users: 3, businessContact: 3 },
    missingFields: ["Уточнить измеримый критерий успеха"],
  },
  {
    id: "task-agro",
    status: "published",
    title: "Мониторинг состояния посевов",
    context: "Агрономы осматривают большие площади вручную.",
    need: "Раньше замечать проблемные зоны.",
    users: "Агрономы",
    data: "Планируется сбор снимков",
    constraints: "Не определены",
    expectedResult: "Карта полей",
    successCriteria: "Требует согласования",
    contact: "agro@example.kz",
    interactionFormat: "Интервью",
    topic: "Агротех",
    score: 37,
    readinessLevel: "draft",
    scoreBreakdown: { contextAndNeed: 10, data: 3, expectedResult: 6, successCriteria: 1, constraints: 0, users: 7, businessContact: 7 },
    missingFields: ["Подтвердить источник данных", "Зафиксировать ограничения", "Добавить метрику успеха"],
  },
] satisfies TaskCard[];

export const taskFixtures = taskCardSchema.array().parse(cards);

export const clarificationFixture: ClarificationResult = clarificationResultSchema.parse({
  mode: "fallback",
  warnings: ["AI-сервис недоступен — использован детерминированный сценарий. Проверьте предложенный текст."],
  questions: [
    { id: "q1", field: "users", text: "Кто будет пользоваться результатом?", hint: "Роль или конкретная команда" },
    { id: "q2", field: "data", text: "Какие данные уже доступны?", hint: "Формат, объём и период" },
    { id: "q3", field: "successCriteria", text: "Как поймём, что решение успешно?", hint: "Измеримый эффект или метрика" },
  ],
  suggestedCard: {
    title: "Помощник для разбора обращений клиентов",
    context: "Команда поддержки вручную читает входящие обращения и распределяет их между специалистами.",
    need: "Нужно быстрее определять тему и приоритет каждого обращения.",
    expectedResult: "Инструмент предлагает категорию и приоритет, а оператор подтверждает решение.",
    constraints: "Персональные данные нельзя отправлять во внешние сервисы.",
    contact: "product@example.kz",
    interactionFormat: "Еженедельное демо с владельцем процесса",
    topic: "Клиентский сервис",
  },
});

export const weakDraft = taskCardSchema.parse({
  id: "task-new",
  status: "draft",
  title: "Помощник для разбора обращений клиентов",
  context: "Команда поддержки вручную разбирает обращения.",
  need: "Нужно ускорить распределение обращений.",
  users: "Операторы поддержки",
  data: "История обращений",
  constraints: "Персональные данные остаются внутри контура",
  expectedResult: "Подсказка категории и приоритета",
  successCriteria: "Сократить время первичной обработки",
  contact: "product@example.kz",
  interactionFormat: "Еженедельное демо",
  topic: "Клиентский сервис",
  score: 48,
  readinessLevel: "workable",
  scoreBreakdown: { contextAndNeed: 10, data: 6, expectedResult: 8, successCriteria: 4, constraints: 4, users: 5, businessContact: 5 },
  missingFields: ["Уточнить объём и формат данных", "Добавить числовую метрику успеха"],
});

export const strongDraft = taskCardSchema.parse({
  ...weakDraft,
  score: 88,
  readinessLevel: "ready",
  scoreBreakdown: { contextAndNeed: 18, data: 17, expectedResult: 13, successCriteria: 12, constraints: 5, users: 5, businessContact: 5 },
  missingFields: ["Уточнить срок пилота"],
});

export const initialProposal: Proposal = proposalSchema.parse({
  id: "proposal-demo",
  taskId: "task-new",
  teamId: "Команда Orbit",
  solutionIdea: "Классификатор с обязательным подтверждением оператора и объяснением уверенности.",
  plan: "Аудит данных, baseline, интерфейс проверки, пилот и оценка метрик.",
  timeline: "4 недели",
  prototypeUrl: "https://example.com/prototype",
  status: "pending",
});
